package ai.elimu.rest.v2.aragon;

import ai.elimu.model.enums.Environment;
import ai.elimu.util.JsonLoader;
import ai.elimu.web.context.EnvironmentContextLoaderListener;
import org.apache.log4j.Logger;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

/**
 * This REST controller simply forwards the JSON response generated by https://github.com/elimu-ai/aragon-dao-webapp
 */
@RestController
@RequestMapping(value = "/rest/v2/aragon", produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
public class AragonRestController {
    
    private Logger logger = Logger.getLogger(getClass());
    
    @RequestMapping(value = "/apps", method = RequestMethod.GET)
    public String handleAppsRequest() {
        logger.info("handleAppsRequest");
        
        String url = getBaseUrl() + "/apps";
        logger.info("url: " + url);
        String jsonResponse = JsonLoader.loadJson(url);
        logger.info("jsonResponse: " + jsonResponse);
        return jsonResponse;
    }
    
    @RequestMapping(value = "/finance-transactions", method = RequestMethod.GET)
    public String handleFinanceTransactionsRequest() {
        logger.info("handleFinanceTransactionsRequest");
        
        String url = getBaseUrl() + "/finance-transactions";
        logger.info("url: " + url);
        String jsonResponse = JsonLoader.loadJson(url);
        logger.info("jsonResponse: " + jsonResponse);
        return jsonResponse;
    }
    
    @RequestMapping(value = "/token-holders", method = RequestMethod.GET)
    public String handleTokensRequest() {
        logger.info("handleTokensRequest");
        
        String url = getBaseUrl() + "/token-holders";
        logger.info("url: " + url);
        String jsonResponse = JsonLoader.loadJson(url);
        logger.info("jsonResponse: " + jsonResponse);
        return jsonResponse;
    }
    
    @RequestMapping(value = "/votes", method = RequestMethod.GET)
    public String handleVotesRequest() {
        logger.info("handleVotesRequest");
        
        String url = getBaseUrl() + "/votes";
        logger.info("url: " + url);
        String jsonResponse = JsonLoader.loadJson(url);
        logger.info("jsonResponse: " + jsonResponse);
        return jsonResponse;
    }
    
    private String getBaseUrl() {
        String domain = "62.75.236.14"; // DEV/TEST
        if (EnvironmentContextLoaderListener.env == Environment.PROD) {
            domain = "85.93.91.26";
        }
        return "http://" + domain + ":3000";
    }
}
