package ai.elimu.entity.enums;

public enum ContentLicense {

    BSD_2_CLAUSE,
    CREATIVE_COMMONS_CC_BY,
    CREATIVE_COMMONS_CC_BY_SA,
    CREATIVE_COMMONS_CC_BY_NC,
    CREATIVE_COMMONS_CC_BY_NC_ND,
    CREATIVE_COMMONS_CC_BY_NC_SA,
    CREATIVE_COMMONS_CC_BY_ND
}
