package ai.elimu.util;

import java.util.Base64;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import ai.elimu.entity.content.multimedia.Image;
import ai.elimu.web.context.EnvironmentContextLoaderListener;
import kong.unirest.core.HttpResponse;
import kong.unirest.core.Unirest;
import lombok.extern.slf4j.Slf4j;

/**
 * Utility class for uploading files to the Large File Storage (LFS) 
 * repo: https://github.com/elimu-ai/webapp-lfs
 */
@Slf4j
public class GitHubLfsHelper {

    /**
     * Upload file to LFS.
     * 
     * @param image The Image to be stored.
     * @return The hash (CID) generated by GitHub.
     */
    public static String uploadImageToLfs(Image image) {
        log.info("uploadImageToLfs");

        // Store file in webapp-lfs
        // https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#create-or-update-file-contents
        
        String languageCode = EnvironmentContextLoaderListener.PROPERTIES.getProperty("content.language");
        log.info("languageCode: " + languageCode);
        
        String filename = image.getId() + "_r" + image.getRevisionNumber() + "." + image.getImageFormat().toString().toLowerCase();
        log.info("filename: " + filename);
        
        String url = "https://api.github.com/repos/elimu-ai/webapp-lfs/contents/" +
            "lang-" + languageCode + "/" +
            "images/" + filename;
        log.info("url: " + url);
        
        JsonObject body = new JsonObject();
        body.addProperty("message", "chore(images): add " + filename);
        body.addProperty("content", Base64.getEncoder().encodeToString(image.getBytes()));
        
        JsonObject committer = new JsonObject();
        committer.addProperty("name", "Nya Ξlimu");
        committer.addProperty("email", "info@elimu.ai");
        body.add("committer", committer);
        log.debug("body: " + body);

        String accessToken = ConfigHelper.getProperty("github.lfs.token");
        HttpResponse<String> httpResponse = Unirest.put(url)
            .header("Authorization", "Bearer " + accessToken)
            .body(body.toString())
            .asString();
        log.info("httpResponse: " + httpResponse);
        log.info("httpResponse.getStatus(): " + httpResponse.getStatus());
        log.info("httpResponse.isSuccess(): " + httpResponse.isSuccess());
        
        JsonObject responseAsJson = JsonParser.parseString(httpResponse.getBody()).getAsJsonObject();
        log.info("responseAsJson.keySet(): " + responseAsJson.keySet());
        if (!httpResponse.isSuccess()) {
            log.warn("responseAsJson: " + responseAsJson);
            return null;
        } else {
            JsonElement contentElement = responseAsJson.get("content");
            log.info("contentElement: " + contentElement);
            String sha = contentElement.getAsJsonObject().get("sha").getAsString();
            log.info("sha: " + sha);
            return sha;
        }
    }
}
