# 1.1.89

ALTER TABLE DbMigration MODIFY script VARCHAR(10000) NOT NULL;

ALTER TABLE Allophone CONVERT TO CHARACTER SET utf8 COLLATE utf8_bin;
ALTER TABLE Letter CONVERT TO CHARACTER SET utf8 COLLATE utf8_bin;
