# 2.0.98

ALTER TABLE SignOnEvent DROP COLUMN referrer;
ALTER TABLE SignOnEvent DROP COLUMN utmSource;
ALTER TABLE SignOnEvent DROP COLUMN utmMedium;
ALTER TABLE SignOnEvent DROP COLUMN utmCampaign;
ALTER TABLE SignOnEvent DROP COLUMN utmTerm;
