# 2.1.14

ALTER TABLE Application CHANGE locale language VARCHAR(255) NOT NULL;

ALTER TABLE Allophone CHANGE locale language VARCHAR(255) COLLATE utf8_bin NOT NULL;
ALTER TABLE Emoji CHANGE locale language VARCHAR(255) COLLATE utf8mb4_bin NOT NULL;
ALTER TABLE Letter CHANGE locale language VARCHAR(255) COLLATE utf8_bin NOT NULL;
ALTER TABLE Number CHANGE locale language VARCHAR(255) NOT NULL;
ALTER TABLE Storybook CHANGE locale language VARCHAR(255) NOT NULL;
ALTER TABLE Syllable CHANGE locale language VARCHAR(255) NOT NULL;
ALTER TABLE Word CHANGE locale language VARCHAR(255) NOT NULL;
ALTER TABLE Audio CHANGE locale language VARCHAR(255) NOT NULL;
ALTER TABLE Image CHANGE locale language VARCHAR(255) NOT NULL;
ALTER TABLE Video CHANGE locale language VARCHAR(255) NOT NULL;

ALTER TABLE Contributor CHANGE locale language VARCHAR(255) DEFAULT NULL;
