name: Maven Regression Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_rest_localhost:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: maven
      - run: mvn clean
      - run: mvn compile
      - run: mvn jetty:run &
      - run: sleep 30
      - run: mvn verify -P regression-test-rest

  test_ui_localhost:
    needs: test_rest_localhost
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: maven
      - run: mvn clean
      - run: mvn compile
      - run: mvn jetty:run &
      - run: sleep 30
      - run: mvn verify -P regression-test-ui -D headless=true
