name: Maven Regression Tests (vie.elimu.ai)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_rest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17
          cache: maven
      - run: mvn verify -P regression-test-rest -D base.url=http://vie.elimu.ai

  test_ui:
    needs: test_rest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17
          cache: maven
      - run: mvn verify -P regression-test-ui -D base.url=http://vie.elimu.ai -D headless=true
